"""Add initial migration

Revision ID: 3a60f9fe24ae
Revises: 
Create Date: 2025-11-28 14:54:41.507047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60f9fe24ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('instagram_username', sa.Text(), nullable=True),
    sa.Column('instagram_password', sa.Text(), nullable=True),
    sa.Column('youtube_client_id', sa.Text(), nullable=True),
    sa.Column('youtube_client_secret', sa.Text(), nullable=True),
    sa.Column('youtube_refresh_token', sa.Text(), nullable=True),
    sa.Column('groq_api_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('makerworld_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('designer_name', sa.String(length=255), nullable=True),
    sa.Column('profile_title', sa.String(length=500), nullable=True),
    sa.Column('profile_designer', sa.String(length=255), nullable=True),
    sa.Column('print_duration', sa.String(length=100), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('material_amount', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('main_image_path', sa.String(length=500), nullable=False),
    sa.Column('additional_images', sa.JSON(), nullable=True),
    sa.Column('instagram_status', sa.String(length=50), nullable=False),
    sa.Column('instagram_post_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_error', sa.Text(), nullable=True),
    sa.Column('instagram_posted_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_status', sa.String(length=50), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=255), nullable=True),
    sa.Column('youtube_error', sa.Text(), nullable=True),
    sa.Column('youtube_posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_makerworld_id'), 'posts', ['makerworld_id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_makerworld_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
